### ISSUE TITLE
quit/replay_confirmquit hooks can't work after recent update

### ISSUE THREAD

**Issue by Katzenwerfer** [juniorsgithub/tf2-loadouts-script#12]
> Disallow aliasing any existing convars that are not movement commands

In a recent update, the ability to alias convars was partially removed.
It's not possible to alias those commands to hook the loadout save aliases anymore.
I have yet to test if that breaks anything in a major way, but I would assume it does.

**Comment by Katzenwerfer** [comment]
This is also an issue with setinfo cvars, which now fully override any aliases.

**Comment by jooonior** [comment]
AFAIK it only broke the automatic save on exit. You could probably work around it by editing your HUD to execute the save script when the quit button is clicked.

Anyways, [v3.0](https://github.com/jooonior/tf2-loadouts-script/releases/tag/v3.0) is up which fixes this by saving the state after every loadout change. If you care to know more about how it works, check out 888bec1. It is slightly heavier than the now broken version, but I could not come up with anything better.
