### ISSUE TITLE
Little Confused

### ISSUE THREAD

**Issue by SashaIndustries** [juniorsgithub/tf2-loadouts-script#4]
In the Class.cfg the example says to have

`alias loadoutA_cfg "exec uber; say_team running uber"`
But I already have
`alias loadoutA_class l9A`

Where do I add.
`alias loadoutA_cfg "exec uber; say_team running uber"`

Has there been a change and the example not updated?
Also group isn't on Steam

**Comment by SashaIndustries** [comment]
Also unsure if the right place but is there a way so on picking a loadout the command is "play (This) (This) or (This) as in rndwave

**Comment by jooonior** [comment]
> But I already have
> `alias loadoutA_class l9A`

It sounds like you're editing `loadout/class.cfg`. Those are "internal" scripts, you should not be touching them.

> Where do I add.
> `alias loadoutA_cfg "exec uber; say_team running uber"`

To your normal `cfg/class.cfg`, or `cfg/user/class.cfg` if you use mastercomfig. Same where you put (or at least should have) the `exec loadouts/class` line .

And ye the Steam group link is dead, I'll remove it.

> Also unsure if the right place but is there a way so on picking a loadout the command is "play (This) (This) or (This) as in rndwave

Don't know what rndwave is but if you want it to play a sound based on what loadout you're on:
```
alias loadoutA_cfg "play vo/halloween_merasmus/sf14_merasmus_minigame_duckhunt_bonusducks_03.mp3"
alias loadoutB_cfg "play <something else>"
```

**Comment by SashaIndustries** [comment]
Thank you very much! rndwave allows you to setup multiple sounds in the
manifest that it will randomly pick from when told to play a file. so like
Dispenser Idle for instance.

Dispenser_Idle.wav by itself just plays itself but you can instead do

rndwave
{
    "wave"     "PathToFile/Dispenser_Idle.wav"
    "wave"     "PathToFile/Dispenser_Idle2.wav"
    "wave"     "PathToFile/UncleDane.wav"
}
Which will mean everytime the dispenser gets put down it will pick one out
at random of the files above that it will play. It will play all of them
before repeating any.

**Comment by jooonior** [comment]
Haven't tried it but you could probably do something like this.
In `game_sounds.txt`:
```
"LoadoutChange.A"
{
	"channel"	"CHAN_STATIC"
	"volume"	"VOL_NORM"
	"soundlevel"  	"SNDLVL_NONE"
	"pitch"		"PITCH_NORM"
	"rndwave"
	{
		"wave"	"ui/tv_tune.wav"
		"wave"	"ui/tv_tune2.wav"
		"wave"	"ui/tv_tune3.wav"
	}
}
```
In your config:
```
alias loadoutA_cfg "playgamesound LoadoutChange.A"
```
