### ISSUE TITLE
i can't leave TF2

### ISSUE THREAD

**Issue by nosh62** [juniorsgithub/tf2-loadouts-script#7]
Whenever I'm trying to leave TF2, the game just doesn't close, and in the console appears:

_Loadout Script working_
_unknown command "build"_
_unknown command "destroy"_

The only way I can leave the game is by ending its task on Task Manager.
I use BudHud and Mastercomfig if that info helps.

**Comment by jooonior** [comment]
There is nothing in the script that prints out `Loadout Script working`, and `build` or `destroy` aren't called either. 
Are you using the v2.0 loadouts.vpk or one of the older versions? Are you sure you're not leaving something out?

**Comment by nosh62** [comment]
Well, I did what was in the instructions, and I downloaded the vpk on the hyperlink.
With some testing, I've found that the vpk for some reason conflicts with my Quick-Build Script for Engineer, and that's the reason why it prints the "unknown command build/destroy".

And what the script prints when the game starts, along with when I try to close it after playing Engineer is:
[Loadouts] Loading save file... 
[Loadouts] Loadouts have been loaded.

And when closing the game:
[Loadouts] Loadouts have been saved. 
Unknown command "destroy"
Unknown command "build"

Do you have any idea of why is this happening? And yes, I've put loadouts.engineer at the end of the Engineer.cfg

**Comment by jooonior** [comment]
Do I understand correctly that if you close TF2 before the engi script is executed, it works? Is it possible that you're using `exit` as an alias name? Something like `alias exit "build 0 0; destroy 0 0"` would produce the exact problem you have. `exit` is a command my script uses to close the game, so by aliasing it to something it would run that something instead of quitting TF2.

**Comment by nosh62** [comment]
Now I've found the issue, the exit teleporter was aliased to exit, going to change it to something else now.
Thanks for the help!
