### ISSUE TITLE
Confused on the 2 step

### ISSUE THREAD

**Issue by MatadorProBr** [juniorsgithub/tf2-loadouts-script#8]
I use Mastercomfig and I already know that I have to change the path (https://docs.mastercomfig.com/latest/setup/install/#custom-configs) to make this script work but, what exaclty path I need to put? I already tried tf/custom/loadouts/load but it doesn't work

**Comment by jooonior** [comment]
Do you already have an autoexec or class CFGs working with mastercomfig?

**Comment by MatadorProBr** [comment]
Yes

**Comment by jooonior** [comment]
Then all you have to do to is add `exec loadouts/load` to your `cfg/user/autoexec.cfg` and for each class `loadouts.<class>` to `cfg/user/<class>.cfg`.

**Comment by MatadorProBr** [comment]
Ok I literally made this same exact thing before and it wasn't working but now it works normally, anyways thx for the help
