### ISSUE TITLE
If you make a hard link (on Windows, not tested on Linux) from `banned_ip.cfg` to `saved_loadouts.txt` you can clear the saved loadouts with the command `writeip`

### ISSUE THREAD

**Issue by chexo3** [juniorsgithub/tf2-loadouts-script#9]
This could be an optional install step/workaround to automagically clear the saved loadouts after loading them.

**Comment by jooonior** [comment]
I've looked into it and turns out there's a similar command that lets me clear the save file directly (see ad9f0f25531aba57ba4a32d101abbf4da8ec14d2). Thanks for the idea.

**Comment by chexo3** [comment]
Ooh clever! I hadn’t thought of using that. Will have to update now, thanks again!
